const clarifaiActionType = {
    FETCH_CLARIFAI_START: 'FETCH_CLARIFAI_START',
    FETCH_CLARIFAI_SUCCESS:'FETCH_CLARIFAI_SUCCESS',
    FETCH_CLARIFAI_FAILED:'FETCH_CLARIFAI_FAILED',
    RESET_CLARIFAI:'RESET_CLARIFAI',
    UPDATE_USER_COUNT_FAILED:'UPDATE_USER_COUNT_FAILED',
    GET_IMAGEURL:'GET_IMAGEURL'
};

export default clarifaiActionType;

