const clarifaiActionType = {
    FETCH_CLARIFAI_START: 'FETCH_CLARIFAI_START',
    FETCH_CLARIFAI_SUCCESS:'FETCH_CLARIFAI_SUCCESS',
    FETCH_CLARIFAI_FAILED:'FETCH_CLARIFAI_FAILED',
    UPDATE_USER_COUNT:'UPDATE_USER_COUNT',
    UPDATE_USER_FAILED:'UPDATE_USER_FAILED',
    GET_IMAGEURL:'GET_IMAGEURL'
};

export default clarifaiActionType;

