export const SignInActtionType = {
  CHANGE_EMAIL_FIELD : 'CHANGE_EMAIL_FIELD',  
  CHANGE_PASSWORD_FIELD : 'CHANGE_PASSWORD_FIELD',
  CHANGE_NAME_FIELD : 'CHANGE_NAME_FIELD',
  REQUEST_USER_PENDING : 'REQUEST_USER_PENDING',
  REQUEST_USER_SUCCESS : 'REQUEST_USER_SUCCESS',
  REQUEST_USER_FAILED : 'REQUEST_USER_FAILED'
};