export const SignInActtionType = {
  CHANGE_EMAIL_FIELD : 'CHANGE_EMAIL_FIELD',  
  CHANGE_PASSWORD_FIELD : 'CHANGE_PASSWORD_FIELD',
  CHANGE_NAME_FIELD : 'CHANGE_NAME_FIELD',
  REQUEST_ROBOTS_PENDING : 'REQUEST_ROBOTS_PENDING',
  REQUEST_ROBOTS_SUCCESS : 'REQUEST_ROBOTS_SUCCESS',
  REQUEST_ROBOTS_FAILED : 'REQUEST_ROBOTS_FAILED'
}