export const userActionType = {
    
    REQUEST_USER_PENDING : 'REQUEST_USER_PENDING',
    REQUEST_USER_SUCCESS : 'REQUEST_USER_SUCCESS',
    REQUEST_USER_FAILED : 'REQUEST_USER_FAILED',
    ROUTE_CHANGE:'ROUTE_CHANGE',
    UPDATE_USER_COUNT:'UPDATE_USER_COUNT'
}