export const userActionType = {
    RESET_CURRENT_USER :'RESET_CURRENT_USER',
    REQUEST_USER_PENDING : 'REQUEST_USER_PENDING',
    REQUEST_USER_SUCCESS : 'REQUEST_USER_SUCCESS',
    REQUEST_USER_FAILED : 'REQUEST_USER_FAILED',
    ROUTE_CHANGE:'ROUTE_CHANGE'
}